# Production Supabase configuration

project_id = "wyyjgpazdytokciipfdd"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://wyyjgpazdytokciipfdd.supabase.co"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[analytics]
enabled = false
